# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.new_note = QtWidgets.QPushButton(self.centralwidget)
        self.new_note.setGeometry(QtCore.QRect(50, 40, 91, 51))
        self.new_note.setStyleSheet("background: rgb(153, 170, 133);\n"
"color: rgb(255, 255, 255)")
        self.new_note.setObjectName("new_note")
        self.note = QtWidgets.QTextEdit(self.centralwidget)
        self.note.setGeometry(QtCore.QRect(270, 90, 521, 441))
        self.note.setObjectName("note")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(270, 60, 521, 20))
        self.name.setStyleSheet("\n"
"color: rgb(255, 255, 255)")
        self.name.setObjectName("name")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(170, 40, 75, 23))
        self.save.setStyleSheet("background: rgb(153, 170, 133);\n"
"color: rgb(255, 255, 255)")
        self.save.setObjectName("save")
        self.delate = QtWidgets.QPushButton(self.centralwidget)
        self.delate.setGeometry(QtCore.QRect(170, 70, 75, 23))
        self.delate.setStyleSheet("background: rgb(153, 170, 133);\n"
"color: rgb(255, 255, 255)")
        self.delate.setObjectName("delate")
        self.list_tag = QtWidgets.QListWidget(self.centralwidget)
        self.list_tag.setGeometry(QtCore.QRect(40, 310, 181, 81))
        self.list_tag.setObjectName("list_tag")
        self.zamitku = QtWidgets.QListWidget(self.centralwidget)
        self.zamitku.setGeometry(QtCore.QRect(40, 120, 171, 161))
        self.zamitku.setObjectName("zamitku")
        self.add_tag = QtWidgets.QPushButton(self.centralwidget)
        self.add_tag.setGeometry(QtCore.QRect(40, 430, 81, 31))
        self.add_tag.setStyleSheet("background: rgb(153, 170, 133);\n"
"color: rgb(255, 255, 255)")
        self.add_tag.setObjectName("add_tag")
        self.delate_tag = QtWidgets.QPushButton(self.centralwidget)
        self.delate_tag.setGeometry(QtCore.QRect(140, 430, 81, 31))
        self.delate_tag.setStyleSheet("background: rgb(153, 170, 133);\n"
"color: rgb(255, 255, 255)")
        self.delate_tag.setObjectName("delate_tag")
        self.sceach = QtWidgets.QPushButton(self.centralwidget)
        self.sceach.setGeometry(QtCore.QRect(150, 490, 91, 31))
        self.sceach.setStyleSheet("background: rgb(153, 170, 133);\n"
"color: rgb(255, 255, 255)")
        self.sceach.setObjectName("sceach")
        self.tag_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.tag_edit.setGeometry(QtCore.QRect(40, 500, 91, 20))
        self.tag_edit.setObjectName("tag_edit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Замітки"))
        self.new_note.setText(_translate("MainWindow", "нова замітка"))
        self.save.setText(_translate("MainWindow", "зберегти"))
        self.delate.setText(_translate("MainWindow", "видалити"))
        self.add_tag.setText(_translate("MainWindow", "додати тег"))
        self.delate_tag.setText(_translate("MainWindow", "видалити тег"))
        self.sceach.setText(_translate("MainWindow", "пошук по тегу"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
